const BUCKET = 'https://huggingface.co/buckets/ktongue/DEM_MCM/resolve/main';

export const skillCategories = [
  {
    category: 'Conception & CAO',
    icon: <img src="/icons/compass.svg" alt="" className="icon-svg" />,
    skills: ['SolidWorks', 'CATIA V5', '3DExperience', 'Sheet Metal', 'Simulation', 'Sustainability/ACV', 'Cotation fonctionnelle', 'DXF'],
  },
  {
    category: 'Simulation & Éléments Finis',
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />,
    skills: ['Abaqus', 'SolidWorks Simulation', 'ANSYS Workbench', 'Cast3M', 'PyMAPDL', 'Solveur 3D Python/C++', 'Statique', 'Modale', 'Dynamique transitoire', 'Thermique', 'FE²', 'Homogénéisation', 'RVE', 'PBC'],
  },
  {
    category: 'Mécanique des Structures',
    icon: <img src="/icons/truss.svg" alt="" className="icon-svg" />,
    skills: ['Milieux Continus', 'Mécanique de la Rupture', 'Fatigue Multiaxiale', 'Dang Van', 'Goodman', 'Dynamique des Structures', 'Mécanique Non Linéaire', 'Contraintes Résiduelles', 'Thermo-élasticité'],
  },
  {
    category: 'Tribologie & Contacts',
    icon: <img src="/icons/gear.svg" alt="" className="icon-svg" />,
    skills: ['Contact Hertzien', 'JKR (Adhésif)', 'Tresca', 'Von Mises', 'Tabor', 'Boussinesq', 'Bourlet', 'Multi-régime', 'Raideur de contact', 'Coefficient de frottement', 'Élastomères'],
  },
  {
    category: 'Fabrication & Procédés',
    icon: <img src="/icons/cnc.svg" alt="" className="icon-svg" />,
    skills: ['Soudure', 'Pliage', 'Découpe laser', 'Tournage', 'Fraisage', 'Injection', 'Fonderie', 'Gammes de fabrication'],
  },
  {
    category: 'Instrumentation & Signal',
    icon: <img src="/icons/signal.svg" alt="" className="icon-svg" />,
    skills: ['Accéléromètres', 'Thermocouples', 'IMU', 'Codeurs', 'Analyse vibratoire', 'AMDEC', 'GR&R', 'Cp/Cpk', 'Spectroscopie laser'],
  },
  {
    category: 'Méthodes Stochastiques',
    icon: <img src="/icons/dice.svg" alt="" className="icon-svg" />,
    skills: ['DEM / LIGGGHTS', 'Chaînes de Markov', 'Monte Carlo', "Plan d'Expériences", "Quantification d'incertitude", 'Surrogate modelling'],
  },
  {
    category: 'IA & Machine Learning',
    icon: <img src="/icons/neurons.svg" alt="" className="icon-svg" />,
    skills: ['PINNs (PyTorch)', 'Identification inverse', 'Deep learning scientifique', 'Data-driven', 'Hyperparameter tuning'],
  },
  {
    category: 'Finance & Gestion',
    icon: <img src="/icons/finance.svg" alt="" className="icon-svg" />,
    skills: ['DCF', 'LBO', 'Analyse financière', 'Modélisation Excel', 'Python financier'],
  },
  {
    category: 'Programmation',
    icon: <img src="/icons/code.svg" alt="" className="icon-svg" />,
    skills: ['Python', 'NumPy', 'SciPy', 'PyTorch', 'Matplotlib', 'OpenCV', 'Pandas', 'C/C++', 'MATLAB', 'Simulink', 'SymPy', 'PyMAPDL', 'LaTeX', 'Git/GitHub', 'Gradio'],
  },
];

export const experiences = [
  {
    icon: <img src="/icons/grad-cap.svg" alt="" className="icon-svg" />,
    title: 'Stage de Master — Couplage Déterministe-Stochastique (DEM + Markov)',
    org: 'IMT Mines Albi & IMT Mines Saint-Étienne',
    orgLogos: ['/logos/albi.png', '/logos/emse.png'],
    date: 'Mar. 2026 – Sep. 2026',
    location: 'Albi / Saint-Étienne',
    details: [
      "Couplage simulations DEM avec chaînes de Markov inhomogènes pour caractériser la ségrégation granulaire.",
      "Extraction de probabilités de transition à l'échelle particulaire depuis les sorties DEM.",
      "Plan d'expériences (DoE) et analyse de sensibilité Monte Carlo pour la quantification d'incertitude.",
      'Pipelines numériques complets en Python (NumPy, SciPy, PyTorch, Matplotlib).',
    ],
    tags: ['DEM', 'Markov', 'Python', 'PyTorch', 'UQ', 'DoE'],
    projectDetail: {
      description: "Couplage simulations DEM (Discrete Element Method) avec chaînes de Markov inhomogènes pour caractériser et prédire la ségrégation granulaire dans un mélangeur à tambour rotatif. Neuf méthodes de partitionnement spatial (cartésien, cylindrique, Voronoï, octree, physique, adaptatif, etc.) sont comparées systématiquement. Les matrices de transition sont construites à partir des trajectoires DEM et propagées pour prédire l'évolution du mélange. Une application Streamlit interactive permet de visualiser les résultats en 3D.",
      repo: 'https://github.com/tiffank1802/MyStudio',
      bucket: 'https://huggingface.co/buckets/ktongue/DEM_MCM',
      images: [
        {
          url: `${BUCKET}/_Good/Experiment/postraitement/voronoi_simulations/voronoi_10cells_NLT3_step157_dt3_tau157_start250/images/etats/etats_espece_small_voronoi_10cells_NLT3_step157_dt3_tau157_start250.png`,
          caption: 'États des espèces — partitionnement Voronoi 10 cellules'
        },
      ],
      links: [
        { label: 'Code source (GitHub)', url: 'https://github.com/tiffank1802/MyStudio', icon: 'github' },
        { label: 'Données brutes (bucket HF)', url: 'https://huggingface.co/buckets/ktongue/DEM_MCM', icon: 'huggingface' },
      ],
    },
  },
  {
    icon: <img src="/icons/chart.svg" alt="" className="icon-svg" />,
    title: 'Projet de Recherche — Solveur EF 3D Non Linéaire (Critère de Dang Van)',
    org: 'Centrale Lyon – ENISE',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: 'Oct. 2025 – Mar. 2026',
    location: 'Saint-Étienne',
    details: [
      "Implémentation d'un solveur éléments finis 3D non linéaire (Python/C++) : statique, modal, dynamique transitoire.",
      'Application et validation du critère de fatigue multiaxiale de Dang Van (méthodologie Agard et al.).',
      'Validation croisée avec solutions analytiques et Abaqus.',
      'Application web déployée sur Hugging Face Spaces.',
    ],
    tags: ['FEM', 'Python', 'C++', 'Dang Van', 'Fatigue', 'Hugging Face'],
  },
  {
    icon: <img src="/icons/neurons.svg" alt="" className="icon-svg" />,
    title: "Projet de Recherche — PINNs pour l'Identification de Matériaux",
    org: 'Centrale Lyon – ENISE (collab. LTDS)',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: '2025',
    location: 'Saint-Étienne',
    details: [
      "Développement d'un PINN sous PyTorch couplant deep learning et contraintes physiques.",
      'Identification inverse des paramètres de loi de comportement depuis essais de compression (LTDS).',
      'Pipeline data-driven complet : prétraitement, entraînement, hyperparamètres, visualisation.',
      'Déployé sur Hugging Face Spaces.',
    ],
    tags: ['PINN', 'PyTorch', 'Inverse', 'Deep Learning', 'LTDS'],
  },
  {
    icon: <img src="/icons/gear.svg" alt="" className="icon-svg" />,
    title: 'Projets Académiques — Tribologie et Contacts Mécaniques',
    org: 'Centrale Lyon – ENISE',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: 'Jan. – Fév. 2026',
    location: 'Saint-Étienne',
    details: [
      'Étude paramétrique du contact hertzien sphère-plan (12 configurations).',
      'Évaluation comparative des critères de limite élastique (Tresca, Von Mises, Tabor) pour 6 matériaux.',
      'Modélisation du contact adhésif (théorie JKR) sur élastomères silicone.',
      'Modélisation multi-régime (élastique, élasto-plastique, plastique).',
    ],
    tags: ['Hertz', 'JKR', 'Tribologie', 'Python', 'FEM'],
  },
  {
    icon: <img src="/icons/axle.svg" alt="" className="icon-svg" />,
    title: 'Projet Académique — Reconception Axe de Roue Motrice (Tracteur Enfant)',
    org: 'Centrale Lyon – ENISE',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: '2025 – 2026',
    location: 'Saint-Étienne',
    details: [
      'Identification des mécanismes de rupture : concentration de contraintes + contraintes résiduelles de traction.',
      'Simulation EF sous SolidWorks Simulation (Von Mises, chargements 500 N + 200 N chaîne).',
      'Solution retenue : contrainte réduite de 450 MPa à 250 MPa, coefficient de sécurité porté de 0,67 à 2,4.',
    ],
    tags: ['SolidWorks', 'FEM', 'Fatigue', 'Conception'],
  },
  {
    icon: <img src="/icons/factory.svg" alt="" className="icon-svg" />,
    title: 'Stage Ingénieur — Diagnostics Industriels & Maintenance Préventive',
    org: 'SOPECAM',
    orgLogos: [],
    date: 'Mai 2024 – Sep. 2024',
    location: 'Yaoundé, Cameroun',
    details: [
      'Analyse des défaillances de pompes sur machines KBA ; stratégies correctives et préventives.',
      "Conception d'un logiciel de gestion du plan de maintenance préventive.",
      'Instrumentation capteurs vibration/température, traitement du signal, AMDEC.',
    ],
    tags: ['AMDEC', 'Capteurs', 'Signal', 'Maintenance'],
  },
  {
    icon: <img src="/icons/cnc.svg" alt="" className="icon-svg" />,
    title: 'Stage Technicien — Conception & Fabrication CNC 3 Axes',
    org: 'FabLab – ENSPY',
    orgLogos: ['/logos/enspy.png'],
    date: 'Mai – Sep. 2023',
    location: 'Yaoundé, Cameroun',
    details: [
      'Conception CAO complète SolidWorks (assemblages, tôlerie, préparation usinage).',
      'Dimensionnement structurel, sélection de composants (guidages, moteurs pas à pas, courroies).',
      'Supervision du montage de la machine CNC 3 axes à usage pédagogique.',
    ],
    tags: ['SolidWorks', 'CNC', 'CAO', 'Fabrication'],
  },
];

export const projects = [
  {
    icon: <img src="/icons/chart.svg" alt="" className="icon-svg" />,
    title: 'FEM Fatigue Solver',
    description: "Solveur EF 3D non linéaire avec critère de fatigue de Dang Van — interface web interactive.",
    details: 'Backend Python/C++, analyses statique/modale/transitoire, détermination du plan critique, validation Abaqus.',
    tags: ['Python', 'C++', 'FEM', 'Dang Van'],
    link: 'https://huggingface.co/spaces/ktongue/simulations_apps',
  },
  {
    icon: <img src="/icons/neurons.svg" alt="" className="icon-svg" />,
    title: 'PINN Material Identification',
    description: "Réseau de neurones physiquement informé pour l'identification inverse de lois de comportement.",
    details: 'Couplage PyTorch + contraintes physiques (élasticité, chaleur, plasticité). Données essais compression LTDS.',
    tags: ['PINN', 'PyTorch', 'Inverse', 'Data-driven'],
    link: 'https://huggingface.co/spaces/ktongue/material_identification',
  },
  {
    icon: <img src="/icons/cart-lift.svg" alt="" className="icon-svg" />,
    title: 'Diable Élévateur Motorisé',
    description: 'Conception complète d\'un diable pour industrie agroalimentaire (sacs 25 kg, cycle ≤ 3 s).',
    details: 'Matrice de choix multicritères, notice de calcul, liasse de définition SolidWorks, ACV avec Sustainability.',
    tags: ['SolidWorks', 'ACV', 'Sheet Metal', 'Cahier des charges'],
  },
  {
    icon: <img src="/icons/grain.svg" alt="" className="icon-svg" />,
    title: 'Modèle de Partitionnement Microstructural',
    description: 'Segmentation d\'images microstructurales et caractérisation statistique des phases.',
    details: 'Traitement d\'images Python (NumPy, OpenCV, SciPy), extraction de caractéristiques géométriques.',
    tags: ['Python', 'OpenCV', 'Segmentation', 'Matériaux'],
  },
  {
    icon: <img src="/icons/engine.svg" alt="" className="icon-svg" />,
    title: 'Architecture PLM — Micro-Moteur',
    description: "Gestion du cycle de vie d'un micro-moteur : structure documentaire PLM complète.",
    details: 'Recensement des documents par composant, processus de validation adapté à chaque mode de fabrication.',
    tags: ['PLM', '3DExperience', 'Cycle de vie'],
  },
  {
    icon: <img src="/icons/books.svg" alt="" className="icon-svg" />,
    title: 'Application Web — Gestion de Bibliothèque',
    description: 'Application full-stack Symfony (PHP) avec architecture MVC et authentification.',
    details: 'Conception base de données, contrôleurs, vues Twig, gestion des utilisateurs et des emprunts.',
    tags: ['Symfony', 'PHP', 'MVC', 'MySQL'],
  },
];

export const academicWorks = [
  {
    icon: <img src="/icons/compass.svg" alt="" className="icon-svg" />, category: 'Dimensionnement',
    semester: 'S9',
    title: 'Conception d\'essieu de tracteur — Analyse EF',
    description: 'Analyse EF complète (SolidWorks Simulation) d\'un essieu de tracteur enfant soumis à rupture répétée : concentration de contraintes, contraintes résiduelles, coefficient de sécurité porté de 0,67 à 2,4. Inclut gamme de fabrication et PLM/SGDT.',
    file: '/rapports/dimensionnement_s9_calcul.pdf',
    size: '11 MB',
    date: 'S9 — 2025/26',
    tags: ['SolidWorks Simulation', 'Von Mises', 'PLM', 'SGDT', 'Gamme fabrication'],
  },
  {
    icon: <img src="/icons/truss.svg" alt="" className="icon-svg" />, category: 'Dimensionnement',
    semester: 'S9',
    title: 'Optimisation Topologique d\'un Piston',
    description: 'Étude et optimisation topologique d\'un piston sous 3DExperience. Conception allégée avec maintien des performances mécaniques.',
    file: null,
    link: 'https://github.com/tiffank1802/ENISE/tree/main/dimensionnement_des_structures-S9',
    size: null,
    date: 'S9 — 2025/26',
    tags: ['3DExperience', 'Optimisation Topologique', 'Conception'],
  },
  {
    icon: <img src="/icons/flame.svg" alt="" className="icon-svg" />, category: 'Dimensionnement',
    semester: 'S9',
    title: 'Couplage Thermo-Mécanique (ANSYS)',
    description: 'Modélisation d\'un flux mobile sur plaque rectangulaire sous ANSYS Workbench. Couplage multiphysique thermique-mécanique par éléments finis.',
    file: null,
    link: 'https://github.com/tiffank1802/ENISE/tree/main/dimensionnement_des_structures-S9',
    size: null,
    date: 'S9 — 2025/26',
    tags: ['ANSYS Workbench', 'Couplage Thermo-Mécanique', 'PyMAPDL'],
  },
  {
    icon: <img src="/icons/compass.svg" alt="" className="icon-svg" />, category: 'Dimensionnement',
    semester: 'S8',
    title: 'Dynamique des Structures & EF 1D/2D',
    description: 'Application de la MEF : études 1D (propagation d\'onde) et 2D (plaque avec trou central, éléments P1). Analyse modale et dynamique transitoire avec MATLAB.',
    file: '/rapports/dimensionnement_s8_dynamique.pdf',
    size: '8.1 MB',
    date: 'S8 — 2025',
    tags: ['MATLAB', 'MEF 1D/2D', 'Éléments P1', 'Dynamique'],
  },
  {
    icon: <img src="/icons/gear.svg" alt="" className="icon-svg" />, category: 'Dimensionnement',
    semester: 'S9',
    title: 'Dynamique des Structures S9',
    description: 'Analyse dynamique des structures : modes propres, fréquences, réponse temporelle. Notebook SymPy et simulations avancées.',
    file: '/rapports/dimensionnement_s9_dynamique.pdf',
    size: '4.8 MB',
    date: 'S9 — 2025/26',
    tags: ['SymPy', 'Dynamique', 'MEF', 'Analyse modale'],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: 'Tribologie',
    semester: 'S8/S9',
    title: 'Contact Hertzien Sphère-Plan',
    description: 'Analyse complète du contact élastique sphère-plan : pression hertzienne, zone de contact, contraintes internes. Étude paramétrique sur 6 matériaux.',
    file: '/rapports/tribologie_principal.pdf',
    size: '718 KB',
    date: 'S8 — 2025',
    tags: ['Hertz', 'Contact', 'Pression', 'Python'],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: 'Tribologie',
    semester: 'S8',
    title: 'Contact Hertzien — 12 Configurations (DM1)',
    description: 'Étude paramétrique du contact sphère-plan pour 12 configurations : variation du matériau et du rayon. Comparaison Tresca/Von Mises, profils de pression et carte de Bourlet.',
    file: '/rapports/tribologie_dm1.pdf',
    size: '1 MB',
    date: 'S8 — 2025',
    tags: ['Hertz', 'Tresca', 'Von Mises', 'Bourlet', '12 cas'],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: 'Tribologie',
    semester: 'S9',
    title: 'Analyse Complète Contacts Non-Adhésifs (DM3)',
    description: 'Analyse des régimes élastique, élasto-plastique et plastique. Raideurs de contact, limites élastiques, comparaison multi-matériaux.',
    file: '/rapports/tribologie_dm3.pdf',
    size: '5.2 MB',
    date: 'S9 — 2025/26',
    tags: ['Multi-régime', 'Raideur', 'Limite élastique', 'Tabor'],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: 'Tribologie',
    semester: 'S9',
    title: 'Effets des Efforts sur les Limites Élastiques (DM31)',
    description: 'Analyse des effets des efforts et pressions sur les limites élastiques pour 6 matériaux. Visualisation des seuils de plasticité.',
    file: '/rapports/tribologie_dm31.pdf',
    size: '1.5 MB',
    date: 'S9 — 2025/26',
    tags: ['Limite élastique', 'Plasticité', 'Python', 'Analyse'],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: 'Tribologie',
    semester: 'S9',
    title: 'Contacts Adhésifs JKR sur Élastomères (DM4)',
    description: 'Modélisation du contact adhésif sphère-plan sur élastomères silicone (théorie JKR). Essais d\'indentation et de frottement, courbes expérimentales.',
    file: '/rapports/tribologie_dm4.pdf',
    size: '714 KB',
    date: 'S9 — 2025/26',
    tags: ['JKR', 'Adhésif', 'Élastomère', 'Frottement'],
  },
  {
    icon: <img src="/icons/fe2.svg" alt="" className="icon-svg" />, category: 'Méthodes Numériques',
    semester: 'S9',
    title: 'Homogénéisation FE² — Matériaux Composites',
    description: 'Homogénéisation par moyenne volumique d\'un composite tissé (TRC) sous Abaqus. Modélisation RVE avec conditions aux limites périodiques (PBCs), approche FE² multi-échelle.',
    file: null,
    link: 'https://github.com/tiffank1802/ENISE/tree/main/Methodes%20numeriques%20avancees',
    size: null,
    date: 'S9 — 2025/26',
    tags: ['FE²', 'Homogénéisation', 'Abaqus', 'RVE', 'PBC', 'Composite'],
  },
  {
    icon: <img src="/icons/finance.svg" alt="" className="icon-svg" />, category: 'Finances',
    semester: 'S8',
    title: 'Acquisition Bricorama — DCF & LBO',
    description: 'Analyse financière complète de l\'acquisition de Bricorama France : valorisation DCF, montage LBO, modélisation Python/Excel, rapports détaillés.',
    file: '/rapports/finances_rapport_final.pdf',
    size: '749 KB',
    date: 'S8 — 2025',
    tags: ['DCF', 'LBO', 'Finance', 'Python', 'Excel'],
  },
];
