const BUCKET = 'https://huggingface.co/buckets/ktongue/DEM_MCM/resolve/main';

export const skillCategories = [
  {
    category: { fr: 'Conception & CAO', en: 'Design & CAD' },
    icon: <img src="/icons/compass.svg" alt="" className="icon-svg" />,
    skills: ['SolidWorks', 'CATIA V5', '3DExperience', 'Sheet Metal', 'Simulation', 'Sustainability/ACV', { fr: 'Cotation fonctionnelle', en: 'Functional Tolerancing' }, 'DXF'],
  },
  {
    category: { fr: 'Simulation & Éléments Finis', en: 'Simulation & Finite Elements' },
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />,
    skills: ['Abaqus', 'SolidWorks Simulation', 'ANSYS Workbench', 'Cast3M', 'PyMAPDL', { fr: 'Solveur 3D Python/C++', en: '3D Python/C++ Solver' }, { fr: 'Statique', en: 'Static' }, { fr: 'Modale', en: 'Modal' }, { fr: 'Dynamique transitoire', en: 'Transient Dynamics' }, { fr: 'Thermique', en: 'Thermal' }, 'FE²', { fr: 'Homogénéisation', en: 'Homogenization' }, 'RVE', 'PBC'],
  },
  {
    category: { fr: 'Mécanique des Structures', en: 'Structural Mechanics' },
    icon: <img src="/icons/truss.svg" alt="" className="icon-svg" />,
    skills: [{ fr: 'Milieux Continus', en: 'Continuum Mechanics' }, { fr: 'Mécanique de la Rupture', en: 'Fracture Mechanics' }, { fr: 'Fatigue Multiaxiale', en: 'Multiaxial Fatigue' }, 'Dang Van', 'Goodman', { fr: 'Dynamique des Structures', en: 'Structural Dynamics' }, { fr: 'Mécanique Non Linéaire', en: 'Nonlinear Mechanics' }, { fr: 'Contraintes Résiduelles', en: 'Residual Stresses' }, { fr: 'Thermo-élasticité', en: 'Thermoelasticity' }],
  },
  {
    category: { fr: 'Tribologie & Contacts', en: 'Tribology & Contacts' },
    icon: <img src="/icons/gear.svg" alt="" className="icon-svg" />,
    skills: [{ fr: 'Contact Hertzien', en: 'Hertzian Contact' }, { fr: 'JKR (Adhésif)', en: 'JKR (Adhesive)' }, 'Tresca', 'Von Mises', 'Tabor', 'Boussinesq', 'Bourlet', { fr: 'Multi-régime', en: 'Multi-regime' }, { fr: 'Raideur de contact', en: 'Contact Stiffness' }, { fr: 'Coefficient de frottement', en: 'Friction Coefficient' }, { fr: 'Élastomères', en: 'Elastomers' }],
  },
  {
    category: { fr: 'Fabrication & Procédés', en: 'Manufacturing & Processes' },
    icon: <img src="/icons/cnc.svg" alt="" className="icon-svg" />,
    skills: [{ fr: 'Soudure', en: 'Welding' }, { fr: 'Pliage', en: 'Bending' }, { fr: 'Découpe laser', en: 'Laser Cutting' }, { fr: 'Tournage', en: 'Turning' }, { fr: 'Fraisage', en: 'Milling' }, { fr: 'Injection', en: 'Injection Molding' }, { fr: 'Fonderie', en: 'Casting' }, { fr: 'Gammes de fabrication', en: 'Manufacturing Routes' }],
  },
  {
    category: { fr: 'Instrumentation & Signal', en: 'Instrumentation & Signal' },
    icon: <img src="/icons/signal.svg" alt="" className="icon-svg" />,
    skills: [{ fr: 'Accéléromètres', en: 'Accelerometers' }, { fr: 'Thermocouples', en: 'Thermocouples' }, 'IMU', { fr: 'Codeurs', en: 'Encoders' }, { fr: 'Analyse vibratoire', en: 'Vibration Analysis' }, 'AMDEC', 'GR&R', 'Cp/Cpk', { fr: 'Spectroscopie laser', en: 'Laser Spectroscopy' }],
  },
  {
    category: { fr: 'Méthodes Stochastiques', en: 'Stochastic Methods' },
    icon: <img src="/icons/dice.svg" alt="" className="icon-svg" />,
    skills: ['DEM / LIGGGHTS', { fr: 'Chaînes de Markov', en: 'Markov Chains' }, 'Monte Carlo', { fr: "Plan d'Expériences", en: 'Design of Experiments' }, { fr: "Quantification d'incertitude", en: 'Uncertainty Quantification' }, 'Surrogate modelling'],
  },
  {
    category: { fr: 'IA & Machine Learning', en: 'AI & Machine Learning' },
    icon: <img src="/icons/neurons.svg" alt="" className="icon-svg" />,
    skills: ['PINNs (PyTorch)', { fr: 'Identification inverse', en: 'Inverse Identification' }, { fr: 'Deep learning scientifique', en: 'Scientific Deep Learning' }, 'Data-driven', 'Hyperparameter tuning'],
  },
  {
    category: { fr: 'Finance & Gestion', en: 'Finance & Management' },
    icon: <img src="/icons/finance.svg" alt="" className="icon-svg" />,
    skills: ['DCF', 'LBO', { fr: 'Analyse financière', en: 'Financial Analysis' }, { fr: 'Modélisation Excel', en: 'Excel Modeling' }, { fr: 'Python financier', en: 'Financial Python' }],
  },
  {
    category: { fr: 'Programmation', en: 'Programming' },
    icon: <img src="/icons/code.svg" alt="" className="icon-svg" />,
    skills: ['Python', 'NumPy', 'SciPy', 'PyTorch', 'Matplotlib', 'OpenCV', 'Pandas', 'C/C++', 'MATLAB', 'Simulink', 'SymPy', 'PyMAPDL', 'LaTeX', 'Git/GitHub', 'Gradio'],
  },
];

export const experiences = [
  {
    icon: <img src="/icons/grad-cap.svg" alt="" className="icon-svg" />,
    title: { fr: 'Stage de Master — Couplage Déterministe-Stochastique (DEM + Markov)', en: 'Master Internship — Deterministic-Stochastic Coupling (DEM + Markov)' },
    org: 'IMT Mines Albi & IMT Mines Saint-Étienne',
    orgLogos: ['/logos/albi.png', '/logos/emse.png'],
    date: 'Mar. 2026 – Sep. 2026',
    location: { fr: 'Albi / Saint-Étienne', en: 'Albi / Saint-Étienne' },
    details: [
      { fr: "Couplage simulations DEM avec chaînes de Markov inhomogènes pour caractériser la ségrégation granulaire.", en: "Coupling DEM simulations with inhomogeneous Markov chains to characterize granular segregation." },
      { fr: "Extraction de probabilités de transition à l'échelle particulaire depuis les sorties DEM.", en: "Extraction of particle-scale transition probabilities from DEM outputs." },
      { fr: "Plan d'expériences (DoE) et analyse de sensibilité Monte Carlo pour la quantification d'incertitude.", en: "Design of Experiments (DoE) and Monte Carlo sensitivity analysis for uncertainty quantification." },
      { fr: 'Pipelines numériques complets en Python (NumPy, SciPy, PyTorch, Matplotlib).', en: 'Complete numerical pipelines in Python (NumPy, SciPy, PyTorch, Matplotlib).' },
    ],
    tags: ['DEM', 'Markov', 'Python', 'PyTorch', 'UQ', 'DoE'],
    projectDetail: {
      description: { fr: "Couplage simulations DEM (Discrete Element Method) avec chaînes de Markov inhomogènes pour caractériser et prédire la ségrégation granulaire dans un mélangeur à tambour rotatif. Neuf méthodes de partitionnement spatial (cartésien, cylindrique, Voronoï, octree, physique, adaptatif, etc.) sont comparées systématiquement. Les matrices de transition sont construites à partir des trajectoires DEM et propagées pour prédire l'évolution du mélange. Une application Streamlit interactive permet de visualiser les résultats en 3D.", en: "Coupling DEM (Discrete Element Method) simulations with inhomogeneous Markov chains to characterize and predict granular segregation in a rotating drum mixer. Nine spatial partitioning methods (Cartesian, cylindrical, Voronoi, octree, physics-based, adaptive, etc.) are systematically compared. Transition matrices are built from DEM trajectories and propagated to predict mixture evolution. An interactive Streamlit app enables 3D visualization of results." },
      repo: 'https://github.com/tiffank1802/MyStudio',
      bucket: 'https://huggingface.co/buckets/ktongue/DEM_MCM',
      images: [
        {
          url: `${BUCKET}/_Good/Experiment/postraitement/voronoi_simulations/voronoi_10cells_NLT3_step157_dt3_tau157_start250/images/etats/etats_espece_small_voronoi_10cells_NLT3_step157_dt3_tau157_start250.png`,
          caption: { fr: 'États des espèces — partitionnement Voronoi 10 cellules', en: 'Species states — Voronoi 10-cell partitioning' }
        },
      ],
      links: [
        { label: { fr: 'Code source (GitHub)', en: 'Source code (GitHub)' }, url: 'https://github.com/tiffank1802/MyStudio', icon: 'github' },
        { label: { fr: 'Données brutes (bucket HF)', en: 'Raw data (HF bucket)' }, url: 'https://huggingface.co/buckets/ktongue/DEM_MCM', icon: 'huggingface' },
      ],
    },
  },
  {
    icon: <img src="/icons/chart.svg" alt="" className="icon-svg" />,
    title: { fr: 'Projet de Recherche — Solveur EF 3D Non Linéaire (Critère de Dang Van)', en: 'Research Project — Nonlinear 3D FE Solver (Dang Van Criterion)' },
    org: 'Centrale Lyon – ENISE',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: { fr: 'Oct. 2025 – Mar. 2026', en: 'Oct. 2025 – Mar. 2026' },
    location: { fr: 'Saint-Étienne', en: 'Saint-Étienne' },
    details: [
      { fr: "Implémentation d'un solveur éléments finis 3D non linéaire (Python/C++) : statique, modal, dynamique transitoire.", en: "Implementation of a nonlinear 3D finite element solver (Python/C++): static, modal, transient dynamics." },
      { fr: 'Application et validation du critère de fatigue multiaxiale de Dang Van (méthodologie Agard et al.).', en: 'Application and validation of the Dang Van multiaxial fatigue criterion (Agard et al. methodology).' },
      { fr: 'Validation croisée avec solutions analytiques et Abaqus.', en: 'Cross-validation with analytical solutions and Abaqus.' },
      { fr: 'Application web déployée sur Hugging Face Spaces.', en: 'Web application deployed on Hugging Face Spaces.' },
    ],
    tags: ['FEM', 'Python', 'C++', 'Dang Van', 'Fatigue', 'Hugging Face'],
  },
  {
    icon: <img src="/icons/neurons.svg" alt="" className="icon-svg" />,
    title: { fr: "Projet de Recherche — PINNs pour l'Identification de Matériaux", en: 'Research Project — PINNs for Material Identification' },
    org: 'Centrale Lyon – ENISE (collab. LTDS)',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: '2025',
    location: { fr: 'Saint-Étienne', en: 'Saint-Étienne' },
    details: [
      { fr: "Développement d'un PINN sous PyTorch couplant deep learning et contraintes physiques.", en: "Development of a PINN in PyTorch coupling deep learning with physical constraints." },
      { fr: 'Identification inverse des paramètres de loi de comportement depuis essais de compression (LTDS).', en: 'Inverse identification of constitutive law parameters from compression tests (LTDS).' },
      { fr: 'Pipeline data-driven complet : prétraitement, entraînement, hyperparamètres, visualisation.', en: 'Complete data-driven pipeline: preprocessing, training, hyperparameters, visualization.' },
      { fr: 'Déployé sur Hugging Face Spaces.', en: 'Deployed on Hugging Face Spaces.' },
    ],
    tags: ['PINN', 'PyTorch', 'Inverse', 'Deep Learning', 'LTDS'],
  },
  {
    icon: <img src="/icons/gear.svg" alt="" className="icon-svg" />,
    title: { fr: 'Projets Académiques — Tribologie et Contacts Mécaniques', en: 'Academic Projects — Tribology and Mechanical Contacts' },
    org: 'Centrale Lyon – ENISE',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: { fr: 'Jan. – Fév. 2026', en: 'Jan. – Feb. 2026' },
    location: { fr: 'Saint-Étienne', en: 'Saint-Étienne' },
    details: [
      { fr: 'Étude paramétrique du contact hertzien sphère-plan (12 configurations).', en: 'Parametric study of sphere-plane Hertzian contact (12 configurations).' },
      { fr: 'Évaluation comparative des critères de limite élastique (Tresca, Von Mises, Tabor) pour 6 matériaux.', en: 'Comparative evaluation of yield criteria (Tresca, Von Mises, Tabor) for 6 materials.' },
      { fr: 'Modélisation du contact adhésif (théorie JKR) sur élastomères silicone.', en: 'Adhesive contact modeling (JKR theory) on silicone elastomers.' },
      { fr: 'Modélisation multi-régime (élastique, élasto-plastique, plastique).', en: 'Multi-regime modeling (elastic, elasto-plastic, plastic).' },
    ],
    tags: ['Hertz', 'JKR', 'Tribologie', 'Python', 'FEM'],
  },
  {
    icon: <img src="/icons/axle.svg" alt="" className="icon-svg" />,
    title: { fr: 'Projet Académique — Reconception Axe de Roue Motrice (Tracteur Enfant)', en: 'Academic Project — Drive Wheel Axle Redesign (Kids Tractor)' },
    org: 'Centrale Lyon – ENISE',
    orgLogos: ['/logos/centrale-lyon.png'],
    date: '2025 – 2026',
    location: { fr: 'Saint-Étienne', en: 'Saint-Étienne' },
    details: [
      { fr: 'Identification des mécanismes de rupture : concentration de contraintes + contraintes résiduelles de traction.', en: 'Identification of failure mechanisms: stress concentration + tensile residual stresses.' },
      { fr: 'Simulation EF sous SolidWorks Simulation (Von Mises, chargements 500 N + 200 N chaîne).', en: 'FE simulation under SolidWorks Simulation (Von Mises, 500 N + 200 N chain loads).' },
      { fr: 'Solution retenue : contrainte réduite de 450 MPa à 250 MPa, coefficient de sécurité porté de 0,67 à 2,4.', en: 'Final solution: stress reduced from 450 MPa to 250 MPa, safety factor increased from 0.67 to 2.4.' },
    ],
    tags: ['SolidWorks', 'FEM', 'Fatigue', 'Conception'],
  },
  {
    icon: <img src="/icons/factory.svg" alt="" className="icon-svg" />,
    title: { fr: 'Stage Ingénieur — Diagnostics Industriels & Maintenance Préventive', en: 'Engineering Internship — Industrial Diagnostics & Preventive Maintenance' },
    org: 'SOPECAM',
    orgLogos: [],
    date: { fr: 'Mai 2024 – Sep. 2024', en: 'May 2024 – Sep. 2024' },
    location: { fr: 'Yaoundé, Cameroun', en: 'Yaoundé, Cameroon' },
    details: [
      { fr: 'Analyse des défaillances de pompes sur machines KBA ; stratégies correctives et préventives.', en: 'Pump failure analysis on KBA machines; corrective and preventive strategies.' },
      { fr: "Conception d'un logiciel de gestion du plan de maintenance préventive.", en: "Design of a preventive maintenance plan management software." },
      { fr: 'Instrumentation capteurs vibration/température, traitement du signal, AMDEC.', en: 'Vibration/temperature sensor instrumentation, signal processing, FMEA.' },
    ],
    tags: ['AMDEC', 'Capteurs', 'Signal', 'Maintenance'],
  },
  {
    icon: <img src="/icons/cnc.svg" alt="" className="icon-svg" />,
    title: { fr: 'Stage Technicien — Conception & Fabrication CNC 3 Axes', en: 'Technician Internship — 3-Axis CNC Design & Manufacturing' },
    org: 'FabLab – ENSPY',
    orgLogos: ['/logos/enspy.png'],
    date: { fr: 'Mai – Sep. 2023', en: 'May – Sep. 2023' },
    location: { fr: 'Yaoundé, Cameroun', en: 'Yaoundé, Cameroon' },
    details: [
      { fr: 'Conception CAO complète SolidWorks (assemblages, tôlerie, préparation usinage).', en: 'Complete SolidWorks CAD design (assemblies, sheet metal, machining preparation).' },
      { fr: 'Dimensionnement structurel, sélection de composants (guidages, moteurs pas à pas, courroies).', en: 'Structural sizing, component selection (guides, stepper motors, belts).' },
      { fr: 'Supervision du montage de la machine CNC 3 axes à usage pédagogique.', en: 'Supervision of 3-axis CNC machine assembly for educational use.' },
    ],
    tags: ['SolidWorks', 'CNC', 'CAO', 'Fabrication'],
  },
];

export const projects = [
  {
    icon: <img src="/icons/chart.svg" alt="" className="icon-svg" />,
    title: 'FEM Fatigue Solver',
    description: { fr: "Solveur EF 3D non linéaire avec critère de fatigue de Dang Van — interface web interactive.", en: "Nonlinear 3D FE solver with Dang Van fatigue criterion — interactive web interface." },
    details: { fr: 'Backend Python/C++, analyses statique/modale/transitoire, détermination du plan critique, validation Abaqus.', en: 'Python/C++ backend, static/modal/transient analyses, critical plane determination, Abaqus validation.' },
    tags: ['Python', 'C++', 'FEM', 'Dang Van'],
    link: 'https://huggingface.co/spaces/ktongue/simulations_apps',
  },
  {
    icon: <img src="/icons/neurons.svg" alt="" className="icon-svg" />,
    title: 'PINN Material Identification',
    description: { fr: "Réseau de neurones physiquement informé pour l'identification inverse de lois de comportement.", en: "Physics-informed neural network for inverse identification of constitutive laws." },
    details: { fr: 'Couplage PyTorch + contraintes physiques (élasticité, chaleur, plasticité). Données essais compression LTDS.', en: 'PyTorch coupling + physical constraints (elasticity, heat, plasticity). LTDS compression test data.' },
    tags: ['PINN', 'PyTorch', 'Inverse', 'Data-driven'],
    link: 'https://huggingface.co/spaces/ktongue/ID_Mat_PINNs',
  },
  {
    icon: <img src="/icons/cart-lift.svg" alt="" className="icon-svg" />,
    title: { fr: 'Diable Élévateur Motorisé', en: 'Motorized Hand Truck' },
    description: { fr: "Conception complète d'un diable pour industrie agroalimentaire (sacs 25 kg, cycle \u2264 3 s).", en: "Complete design of a hand truck for the agri-food industry (25 kg bags, cycle \u2264 3 s)." },
    details: { fr: 'Matrice de choix multicritères, notice de calcul, liasse de définition SolidWorks, ACV avec Sustainability.', en: 'Multi-criteria decision matrix, calculation report, SolidWorks definition package, LCA with Sustainability.' },
    tags: ['SolidWorks', 'ACV', 'Sheet Metal', { fr: 'Cahier des charges', en: 'Specifications' }],
  },
  {
    icon: <img src="/icons/grain.svg" alt="" className="icon-svg" />,
    title: { fr: 'Modèle de Partitionnement Microstructural', en: 'Microstructural Partitioning Model' },
    description: { fr: "Segmentation d'images microstructurales et caractérisation statistique des phases.", en: "Microstructural image segmentation and statistical phase characterization." },
    details: { fr: "Traitement d'images Python (NumPy, OpenCV, SciPy), extraction de caractéristiques géométriques.", en: "Python image processing (NumPy, OpenCV, SciPy), geometric feature extraction." },
    tags: ['Python', 'OpenCV', { fr: 'Segmentation', en: 'Segmentation' }, { fr: 'Matériaux', en: 'Materials' }],
  },
  {
    icon: <img src="/icons/engine.svg" alt="" className="icon-svg" />,
    title: { fr: 'Architecture PLM — Micro-Moteur', en: 'PLM Architecture — Micro-Motor' },
    description: { fr: "Gestion du cycle de vie d'un micro-moteur : structure documentaire PLM complète.", en: "Lifecycle management of a micro-motor: complete PLM document structure." },
    details: { fr: 'Recensement des documents par composant, processus de validation adapté à chaque mode de fabrication.', en: 'Document inventory by component, validation process adapted to each manufacturing method.' },
    tags: ['PLM', '3DExperience', { fr: 'Cycle de vie', en: 'Lifecycle' }],
  },
  {
    icon: <img src="/icons/books.svg" alt="" className="icon-svg" />,
    title: { fr: 'Application Web — Gestion de Bibliothèque', en: 'Web App — Library Management' },
    description: { fr: 'Application full-stack Symfony (PHP) avec architecture MVC et authentification.', en: 'Full-stack Symfony (PHP) app with MVC architecture and authentication.' },
    details: { fr: 'Conception base de données, contrôleurs, vues Twig, gestion des utilisateurs et des emprunts.', en: 'Database design, controllers, Twig views, user and loan management.' },
    tags: ['Symfony', 'PHP', 'MVC', 'MySQL'],
  },
];

export const academicWorks = [
  {
    icon: <img src="/icons/compass.svg" alt="" className="icon-svg" />, category: { fr: 'Dimensionnement', en: 'Design' },
    semester: 'S9',
    title: { fr: "Conception d'essieu de tracteur — Analyse EF", en: 'Tractor Axle Design — FE Analysis' },
    description: { fr: "Analyse EF complète (SolidWorks Simulation) d'un essieu de tracteur enfant soumis à rupture répétée : concentration de contraintes, contraintes résiduelles, coefficient de sécurité porté de 0,67 à 2,4. Inclut gamme de fabrication et PLM/SGDT.", en: "Complete FE analysis (SolidWorks Simulation) of a kids' tractor axle subjected to repeated failure: stress concentration, residual stresses, safety factor increased from 0.67 to 2.4. Includes manufacturing route and PLM/GDT." },
    file: '/rapports/dimensionnement_s9_calcul.pdf',
    size: '11 MB',
    date: 'S9 — 2025/26',
    tags: ['SolidWorks Simulation', 'Von Mises', 'PLM', 'SGDT', { fr: 'Gamme fabrication', en: 'Manufacturing route' }],
  },
  {
    icon: <img src="/icons/truss.svg" alt="" className="icon-svg" />, category: { fr: 'Dimensionnement', en: 'Design' },
    semester: 'S9',
    title: { fr: "Optimisation Topologique d'un Piston", en: 'Topological Optimization of a Piston' },
    description: { fr: "Étude et optimisation topologique d'un piston sous 3DExperience. Conception allégée avec maintien des performances mécaniques.", en: "Study and topological optimization of a piston under 3DExperience. Lightweight design while maintaining mechanical performance." },
    file: null,
    link: 'https://github.com/tiffank1802/ENISE/tree/main/dimensionnement_des_structures-S9',
    size: null,
    date: 'S9 — 2025/26',
    tags: ['3DExperience', { fr: 'Optimisation Topologique', en: 'Topological Optimization' }, { fr: 'Conception', en: 'Design' }],
  },
  {
    icon: <img src="/icons/flame.svg" alt="" className="icon-svg" />, category: { fr: 'Dimensionnement', en: 'Design' },
    semester: 'S9',
    title: { fr: 'Couplage Thermo-Mécanique (ANSYS)', en: 'Thermo-Mechanical Coupling (ANSYS)' },
    description: { fr: "Modélisation d'un flux mobile sur plaque rectangulaire sous ANSYS Workbench. Couplage multiphysique thermique-mécanique par éléments finis.", en: "Modeling of a moving heat flux on a rectangular plate under ANSYS Workbench. Multiphysics thermal-mechanical coupling via finite elements." },
    file: null,
    link: 'https://github.com/tiffank1802/ENISE/tree/main/dimensionnement_des_structures-S9',
    size: null,
    date: 'S9 — 2025/26',
    tags: ['ANSYS Workbench', { fr: 'Couplage Thermo-Mécanique', en: 'Thermo-Mechanical Coupling' }, 'PyMAPDL'],
  },
  {
    icon: <img src="/icons/compass.svg" alt="" className="icon-svg" />, category: { fr: 'Dimensionnement', en: 'Design' },
    semester: 'S8',
    title: { fr: 'Dynamique des Structures & EF 1D/2D', en: 'Structural Dynamics & 1D/2D FE' },
    description: { fr: "Application de la MEF : études 1D (propagation d'onde) et 2D (plaque avec trou central, éléments P1). Analyse modale et dynamique transitoire avec MATLAB.", en: "FEM application: 1D (wave propagation) and 2D (plate with central hole, P1 elements) studies. Modal and transient dynamic analysis with MATLAB." },
    file: '/rapports/dimensionnement_s8_dynamique.pdf',
    size: '8.1 MB',
    date: 'S8 — 2025',
    tags: ['MATLAB', { fr: 'MEF 1D/2D', en: '1D/2D FEM' }, { fr: 'Éléments P1', en: 'P1 Elements' }, { fr: 'Dynamique', en: 'Dynamics' }],
  },
  {
    icon: <img src="/icons/gear.svg" alt="" className="icon-svg" />, category: { fr: 'Dimensionnement', en: 'Design' },
    semester: 'S9',
    title: { fr: 'Dynamique des Structures S9', en: 'Structural Dynamics S9' },
    description: { fr: 'Analyse dynamique des structures : modes propres, fréquences, réponse temporelle. Notebook SymPy et simulations avancées.', en: 'Structural dynamic analysis: eigenmodes, frequencies, time response. SymPy notebook and advanced simulations.' },
    file: '/rapports/dimensionnement_s9_dynamique.pdf',
    size: '4.8 MB',
    date: 'S9 — 2025/26',
    tags: ['SymPy', { fr: 'Dynamique', en: 'Dynamics' }, 'MEF', { fr: 'Analyse modale', en: 'Modal analysis' }],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: { fr: 'Tribologie', en: 'Tribology' },
    semester: 'S8/S9',
    title: { fr: 'Contact Hertzien Sphère-Plan', en: 'Sphere-Plane Hertzian Contact' },
    description: { fr: 'Analyse complète du contact élastique sphère-plan : pression hertzienne, zone de contact, contraintes internes. Étude paramétrique sur 6 matériaux.', en: 'Complete analysis of elastic sphere-plane contact: Hertzian pressure, contact area, internal stresses. Parametric study on 6 materials.' },
    file: '/rapports/tribologie_principal.pdf',
    size: '718 KB',
    date: 'S8 — 2025',
    tags: ['Hertz', { fr: 'Contact', en: 'Contact' }, { fr: 'Pression', en: 'Pressure' }, 'Python'],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: { fr: 'Tribologie', en: 'Tribology' },
    semester: 'S8',
    title: { fr: 'Contact Hertzien — 12 Configurations (DM1)', en: 'Hertzian Contact — 12 Configurations (DM1)' },
    description: { fr: 'Étude paramétrique du contact sphère-plan pour 12 configurations : variation du matériau et du rayon. Comparaison Tresca/Von Mises, profils de pression et carte de Bourlet.', en: 'Parametric study of sphere-plane contact for 12 configurations: material and radius variation. Tresca/Von Mises comparison, pressure profiles, and Bourlet map.' },
    file: '/rapports/tribologie_dm1.pdf',
    size: '1 MB',
    date: 'S8 — 2025',
    tags: ['Hertz', 'Tresca', 'Von Mises', 'Bourlet', { fr: '12 cas', en: '12 cases' }],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: { fr: 'Tribologie', en: 'Tribology' },
    semester: 'S9',
    title: { fr: 'Analyse Complète Contacts Non-Adhésifs (DM3)', en: 'Complete Non-Adhesive Contact Analysis (DM3)' },
    description: { fr: 'Analyse des régimes élastique, élasto-plastique et plastique. Raideurs de contact, limites élastiques, comparaison multi-matériaux.', en: 'Analysis of elastic, elasto-plastic and plastic regimes. Contact stiffnesses, elastic limits, multi-material comparison.' },
    file: '/rapports/tribologie_dm3.pdf',
    size: '5.2 MB',
    date: 'S9 — 2025/26',
    tags: [{ fr: 'Multi-régime', en: 'Multi-regime' }, { fr: 'Raideur', en: 'Stiffness' }, { fr: 'Limite élastique', en: 'Elastic limit' }, 'Tabor'],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: { fr: 'Tribologie', en: 'Tribology' },
    semester: 'S9',
    title: { fr: 'Effets des Efforts sur les Limites Élastiques (DM31)', en: 'Effects of Loads on Elastic Limits (DM31)' },
    description: { fr: 'Analyse des effets des efforts et pressions sur les limites élastiques pour 6 matériaux. Visualisation des seuils de plasticité.', en: 'Analysis of load and pressure effects on elastic limits for 6 materials. Visualization of plasticity thresholds.' },
    file: '/rapports/tribologie_dm31.pdf',
    size: '1.5 MB',
    date: 'S9 — 2025/26',
    tags: [{ fr: 'Limite élastique', en: 'Elastic limit' }, { fr: 'Plasticité', en: 'Plasticity' }, 'Python', { fr: 'Analyse', en: 'Analysis' }],
  },
  {
    icon: <img src="/icons/sphere.svg" alt="" className="icon-svg" />, category: { fr: 'Tribologie', en: 'Tribology' },
    semester: 'S9',
    title: { fr: 'Contacts Adhésifs JKR sur Élastomères (DM4)', en: 'JKR Adhesive Contacts on Elastomers (DM4)' },
    description: { fr: "Modélisation du contact adhésif sphère-plan sur élastomères silicone (théorie JKR). Essais d'indentation et de frottement, courbes expérimentales.", en: "Modeling of sphere-plane adhesive contact on silicone elastomers (JKR theory). Indentation and friction tests, experimental curves." },
    file: '/rapports/tribologie_dm4.pdf',
    size: '714 KB',
    date: 'S9 — 2025/26',
    tags: ['JKR', { fr: 'Adhésif', en: 'Adhesive' }, { fr: 'Élastomère', en: 'Elastomer' }, { fr: 'Frottement', en: 'Friction' }],
  },
  {
    icon: <img src="/icons/fe2.svg" alt="" className="icon-svg" />, category: { fr: 'Méthodes Numériques', en: 'Numerical Methods' },
    semester: 'S9',
    title: { fr: "Homogénéisation FE² — Matériaux Composites", en: "FE² Homogenization — Composite Materials" },
    description: { fr: "Homogénéisation par moyenne volumique d'un composite tissé (TRC) sous Abaqus. Modélisation RVE avec conditions aux limites périodiques (PBCs), approche FE² multi-échelle.", en: "Volume average homogenization of a woven composite (TRC) under Abaqus. RVE modeling with periodic boundary conditions (PBCs), multi-scale FE² approach." },
    file: null,
    link: 'https://github.com/tiffank1802/ENISE/tree/main/Methodes%20numeriques%20avancees',
    size: null,
    date: 'S9 — 2025/26',
    tags: ['FE²', { fr: 'Homogénéisation', en: 'Homogenization' }, 'Abaqus', 'RVE', 'PBC', { fr: 'Composite', en: 'Composite' }],
  },
  {
    icon: <img src="/icons/finance.svg" alt="" className="icon-svg" />, category: { fr: 'Finances', en: 'Finance' },
    semester: 'S8',
    title: { fr: 'Acquisition Bricorama — DCF & LBO', en: 'Bricorama Acquisition — DCF & LBO' },
    description: { fr: "Analyse financière complète de l'acquisition de Bricorama France : valorisation DCF, montage LBO, modélisation Python/Excel, rapports détaillés.", en: "Complete financial analysis of Bricorama France acquisition: DCF valuation, LBO structuring, Python/Excel modeling, detailed reports." },
    file: '/rapports/finances_rapport_final.pdf',
    size: '749 KB',
    date: 'S8 — 2025',
    tags: ['DCF', 'LBO', { fr: 'Finance', en: 'Finance' }, 'Python', 'Excel'],
  },
];
